# Generated by Django 2.2 on 2021-08-03 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bound_api', '0003_auto_20210803_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('status', models.CharField(choices=[('AC', 'Accepted'), ('DC', 'Decline')], default='DC', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bound_api.User')),
            ],
        ),
    ]
