# Generated by Django 2.2 on 2021-08-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bound_api', '0005_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
