# Generated by Django 2.2 on 2021-08-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bound_api', '0007_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
