# Generated by Django 2.2 on 2021-08-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bound_api', '0010_ordersusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='for_whow_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='from_whow_id',
        ),
        migrations.AddField(
            model_name='order',
            name='for_whom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_whom_order', to='bound_api.OrdersUsers'),
        ),
        migrations.AddField(
            model_name='order',
            name='from_whom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_whom_order', to='bound_api.OrdersUsers'),
        ),
    ]
