# Generated by Django 2.2 on 2021-08-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bound_api', '0012_payment_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
