# Generated by Django 2.2 on 2021-08-24 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bound_api', '0014_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='to_address',
        ),
        migrations.AddField(
            model_name='address',
            name='addresable_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='addresable_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photoable_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photoable_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
