# Generated by Django 2.2 on 2021-08-25 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bound_api', '0015_auto_20210824_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='addresable_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='addresable_type',
        ),
        migrations.AddField(
            model_name='order',
            name='from_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_address_order', to='bound_api.Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='to_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_address_order', to='bound_api.Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bound_api.User'),
        ),
    ]
