# Generated by Django 2.2 on 2021-08-25 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bound_api', '0016_auto_20210825_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='addresable_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='addresable_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
