# Generated by Django 2.2 on 2021-08-25 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bound_api', '0017_auto_20210825_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='from_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bound_api.User'),
        ),
    ]
