# Generated by Django 2.2 on 2021-08-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bound_api', '0020_auto_20210825_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='addresable_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='addresable_id',
            new_name='object_id',
        ),
    ]
