# Generated by Django 2.2 on 2021-08-26 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bound_api', '0022_remove_payment_payment_method_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='bound_api.User'),
        ),
    ]
