# Generated by Django 2.2 on 2021-08-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bound_api', '0024_payment_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photoable_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photoable_id',
            new_name='object_id',
        ),
    ]
