# Generated by Django 2.2 on 2021-08-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0003_auto_20210809_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='model',
            new_name='model_car',
        ),
    ]
