# Generated by Django 2.2 on 2021-08-24 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0004_auto_20210822_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersdrivers',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_drivers', to='driver_app.Driver'),
        ),
        migrations.AlterField(
            model_name='ordersdrivers',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_drivers', to='bound_api.Order'),
        ),
    ]
