from .order_serializer import OrderSerializer
from .user_serializer import UserSerializer
from .registration_serializer import RegistrationSerializer
from .login_serializer import LoginSerializer
from .address_serializer import AddressSerializer
from .payment_method_serializer import PaymentMethodSerializer
from .payment_serializer import PaymentSerializer
from .photo_serializer import PhotoSerializer
